Check whether post-testing .tmp is empty
Co-authored-by: Benjamin Bannier <benjamin.bannier@corelight.com>

diff --git a/testing/Makefile b/testing/Makefile
--- a/testing/Makefile
+++ b/testing/Makefile
@@ -1,6 +1,11 @@
 
 all:
 	@../btest -j -d -f diag.log
+	@if [ -d .tmp ] && [ "$$(ls -A .tmp)" ]; then \
+	    echo "ERROR: Left-over files in .tmp"; \
+	    ls -lA .tmp; \
+	    exit 1; \
+	fi
 
 cleanup:
 	@rm -f diag.log
